name: CI

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    timeout-minutes: 5
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Display Go version
        run: go version
      - name: Test
        run: go test -v -cover
        env:
          GOCONFIG_DEBUG: 1
